export const SUPPORT_INSTITUTION_NAME_MAX_LENGTH = 160;
export const SUPPORT_DESCRIPTION_MAX_LENGTH = 1200;
export const SUPPORT_PHONE_MAX_LENGTH = 40;
export const SUPPORT_EMAIL_MAX_LENGTH = 180;
export const SUPPORT_LOCATION_MAX_LENGTH = 160;
export const SUPPORT_SCHEDULE_MAX_LENGTH = 180;
