export const STORY_TITLE_MAX_LENGTH = 160;
export const STORY_DESCRIPTION_MAX_LENGTH = 1200;
export const STORY_URL_MAX_LENGTH = 500;
export const STORY_CHAPTER_TITLE_MAX_LENGTH = 160;
export const STORY_CHAPTER_CONTENT_MAX_LENGTH = 30000;
export const STORY_CHAPTER_SUMMARY_MAX_LENGTH = 800;
