export const RESOURCE_TITLE_MAX_LENGTH = 255;
export const RESOURCE_TYPE_MAX_LENGTH = 120;
export const RESOURCE_FILE_URL_MAX_LENGTH = 2048;
export const RESOURCE_DESCRIPTION_MAX_LENGTH = 5000;
export const RESOURCE_TAG_MAX_LENGTH = 80;
export const RESOURCE_TAGS_MAX_COUNT = 30;
