export const ALLY_INSTITUTION_NAME_MAX_LENGTH = 255;
export const ALLY_ROLE_LABEL_MAX_LENGTH = 120;
export const ALLY_SUMMARY_MAX_LENGTH = 5000;
export const ALLY_PARTICIPATION_SCOPE_MAX_LENGTH = 5000;
