export const NEWS_TITLE_MAX_LENGTH = 255;
export const NEWS_SLUG_MAX_LENGTH = 180;
export const NEWS_EXCERPT_MAX_LENGTH = 300;
export const NEWS_BODY_MAX_LENGTH = 50000;
export const NEWS_COVER_IMAGE_URL_MAX_LENGTH = 2048;
export const NEWS_COVER_IMAGE_ALT_MAX_LENGTH = 180;
export const NEWS_AUTHOR_NAME_MAX_LENGTH = 120;
